name: Check Environment

on:
  workflow_dispatch:

jobs:
  assemble-release:
    runs-on: ubuntu-latest
    environment: Workflow

    steps:
      - name: Use environment variable
        run: echo "${{ vars.TEST }}"
